version: "3.8"

services:
  api:
    image: node:16.15.1-bullseye
    command: >
      sh -c "apt install -y python3 && cd /usr/src/app/ && 
            yarn install && 
            export NODE_ENV=dev && 
            yarn watch"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 9001:9001
    depends_on:
      - db
  db:
    image: postgres:13.0-alpine
    volumes:
      - ./dump.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=challenge
    ports:
      - 5433:5432

volumes:
  postgres_data:
